#!/bin/bash

set -e

# Only install if FZF doesn't already exist
if [ ! -d "${HOME}/.fzf" ]; then
	echo "Installing FZF..."
	git clone --depth 1 https://github.com/junegunn/fzf.git "${HOME}/.fzf"
	"${HOME}/.fzf/install" --all
else
	echo "FZF already installed, skipping..."
fi

# Ensure ~/.fzf.zsh exists (generated by fzf install --all, but double-check)
if [ ! -f "${HOME}/.fzf.zsh" ] && [ -f "${HOME}/.fzf/shell/completion.zsh" ]; then
	echo "Generating ~/.fzf.zsh..."
	cat >"${HOME}/.fzf.zsh" <<'EOF'
# Setup fzf
if [[ ! "$PATH" == *$HOME/.fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}$HOME/.fzf/bin"
fi

# Auto-completion
[[ $- == *i* ]] && source "$HOME/.fzf/shell/completion.zsh" 2> /dev/null

# Key bindings
source "$HOME/.fzf/shell/key-bindings.zsh"
EOF
	echo "~/.fzf.zsh created."
fi
